### ISSUE TITLE
Should submodules automatically track the latest on their branch?

### ISSUE THREAD

**Issue by dsjoerg** [ggtracker/ggtrackerstack#34]
Currently our submodules are fixed to specific commits.
Would it be better if they automatically tracked the latest?

See http://stackoverflow.com/questions/9189575/git-submodule-tracking-latest for a discussion of how to do this.   However I'm no git expert so I'm not sure how "automatic" the resulting solutions really are.

@nickelsen what do you think?

**Comment by nickelsen** [comment]
Yes, something like this is definitely needed for us to stay sane - both for ggpyjobs in esdb and for the repos in ggtrackerstack. I'll try to see if I can get it working with the help in the link.
