### ISSUE TITLE
minimap replay is out of sync

### ISSUE THREAD

**Issue by dsjoerg** [ggtracker/ggtrackerstack#35]
see https://github.com/ggtracker/sc2reader/pull/10#issuecomment-211617073

**Comment by dsjoerg** [comment]
Fixed by @gravelweb with https://github.com/ggtracker/sc2reader/commit/73d11a9a1cd7bd2a2991014bc9f7352c394d83d0

**Comment by dsjoerg** [comment]
Deployed and working in production!   Any new replays uploaded (or re-uploaded) will get the fixed minimap.  Thanks @gravelweb!

**Comment by dsjoerg** [comment]
Actually @nickelsen fixed this particular issue with https://github.com/dsjoerg/ggtracker/commit/29995cb9bb8ec0543d982dcfa1b22125b4383d42

**Comment by gravelweb** [comment]
Thanks @dsjoerg! Hoping to find time to contribute more soon. Thanks for your support!

**Comment by gravelweb** [comment]
Yes, you meant #7 :)
