### ISSUE TITLE
credit recent contributors

### ISSUE THREAD

**Issue by dsjoerg** [ggtracker/ggtrackerstack#38]
@nickelsen how would you like to be credited on the FAQ?  I was going to write [Anders Nickelsen](https://twitter.com/anickelsen) built ggtrackerstack and initiated active development for the LotV era, with additional contributions from @gravelweb.

@gravelweb how would you like to be credited?  Do you have a twitter or should I just refer to you as @gravelweb @ github?

**Comment by nickelsen** [comment]
That sounds very good to me. :-)

**Comment by gravelweb** [comment]
That's cool :) thanks! Don't really have a respectable social identity, so gravelweb@github is just fine for the time being.

**Comment by dsjoerg** [comment]
Done and in production!
