### ISSUE TITLE
3.4.0 Patch - ~50% of replays don't work

### ISSUE THREAD

**Issue by gravelweb** [ggtracker/ggtrackerstack#52]
I took a quick look and I believe the problem is that the wrong abilities are being picked up by the replay. For example, one game I'm looking at has a Terran using the 'ChronoBoost' Ability.

[issueYY.SC2Replay.zip](https://github.com/ggtracker/ggtrackerstack/files/360607/issueYY.SC2Replay.zip)

**Comment by dsjoerg** [comment]
argggh OK will look into it tomorrow

**Comment by dsjoerg** [comment]
OK have a breaking test with this replay: https://github.com/dsjoerg/ggpyjobs/commit/7c0b1a41446a9c9f132e8c03538144cb69bb481c

Indeed something weird going on with abilities, here's the stacktrace: https://gist.github.com/dsjoerg/5ef6312c5eaa90eaf629fd9038c88ca1

**Comment by dsjoerg** [comment]
However now that I think about it, that is super weird because I was able to parse the exact same replay just fine using sc2reader.  Now I have my WTF moment, hopefully this leads somewhere.

**Comment by dsjoerg** [comment]
Very strange, sc2reader thinks there's a DecloakGhost ability used in the first 30 seconds of the replay: https://gist.github.com/dsjoerg/bd23f72fd32900d9aac36eff7c309792

**Comment by dsjoerg** [comment]
OK I think we either need to run sc2dump.cpp or perhaps simply do an "Export Balance Data" from the galaxy editor.

**Comment by dsjoerg** [comment]
@gravelweb @nickelsen @fx if you're around can you do an Export Balance Data using SC2 3.4 and post the resulting files?  And/or run sc2dump.cpp?

**Comment by dsjoerg** [comment]
Let's keep it simple, I have an email from Sept 2015 from @GraylinKim confirming "Yes all of the ability/unit data is in there" re the "Export Balance Data"

**Comment by fx** [comment]
Don't have time to get myself back into the stack right now, it's been too long, sorry.

**Comment by nickelsen** [comment]
I have the export running now for the first time ever, so I'll try and get some results and post them here.

**Comment by nickelsen** [comment]
[balance-data-3.4-2016-07-13.zip](https://github.com/ggtracker/ggtrackerstack/files/361904/balance-data-3.4-2016-07-13.zip)

I chose Export Balance Data -> LotV. It said that the export failed due to a fatal error, but the log only showed warnings about localization files missing. I don't know if that's a big deal, but here is the zipped contents of the folder I pointed it to.

**Comment by dsjoerg** [comment]
Thanks!  I also have the data from @EHadoux.  Next question is how to turn this data into the files of the kind we see in data/LotV/*.csv.  I have an email out to @GraylinKim asking, as I'm trying to feed kids lunch at the moment :\

**Comment by dsjoerg** [comment]
If any of you are capable of compiling and running a C++ executable on a Windoze box, you would save the day: https://github.com/ggtracker/sc2reader/blob/upstream/sc2dump.cpp

**Comment by gravelweb** [comment]
I have windoze on an old laptop. Let me try to resurrect it.

**Comment by gravelweb** [comment]
Unfortunately my laptop is no longer in the land of the living. No other windows box available atm. Sorry!

**Comment by dsjoerg** [comment]
OK @gravelweb that replay is working now!  http://ggtracker.com/matches/6726920

Will close this issue the failure rate drops back to usual.

**Comment by gravelweb** [comment]
\o/

I take it the CSV with all the abilities needed to be regenerated for 3.4?

**Comment by dsjoerg** [comment]
@gravelweb yep.  will post about how i did it, i used the Balance Data which hadn't been done before.

so far the new code has handled 10 out of 10 replays successfully, a lot better than the old 36% failure rate.

**Comment by dsjoerg** [comment]
28 out of 28 handled correctly.  added a HOWTO: https://github.com/ggtracker/sc2reader/commit/a131d50f31bf30d431157c8670d51b1e492ae9ea

victory!
